### ISSUE TITLE
Extra "]" in facex.py line 31

### ISSUE THREAD

**Issue by ricgene** [hfahrudin/facex#1]
First - this is a cool package!  I used it and got these correct results on a family photo.

{'anger': 1.6111963e-09,
 'disgust': 0.00028076128,
 'fear': 0.0015364134,
 'happy': 0.96373373,
 'neutral': 9.76865e-07,
 'sadness': 0.007112703,
 'surprised': 0.027335346}

OK, on to the issue.  This is in facex 1.0.0.

  File "/usr/local/lib/python3.7/site-packages/facex/facex.py", line 31
    return dict(zip(cat, res[0]))]
                                 ^
SyntaxError: invalid syntax

When I removed the closed bracket, the code ran.
Richard

**Comment by ricgene** [comment]
This is in facex-1.0.0

**Comment by hfahrudin** [comment]
Thanks for reporting! It's always this little thing that makes your code won't work arent they? i will fix it.

**Comment by ricgene** [comment]
Yes - these little things are a pain.  You build 99.999% and then that .001 % needs to be fixed again - it's just that way :-).  Thank you for sharing this cool work!
