### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by iamthinbaker** [hfahrudin/facex#2]
Hi! 

First of all thank you for sharing the code and the trained model in a public repo. It was really helpful. I wonder if the models "model_optimized.tflite" and "model.tflite" has been trained with gray images.  During the inference you pass the faces cropped from the image in gray scale but que tensor input has 3 channels. Is there any reason? Thank you!

**Comment by hfahrudin** [comment]
Im sorry for the late late reply since somehow missed the notification about this issues . It shouldn't be necessary to pass the grayscale image as 3 channel. In this case, i just forgot to properly preprocess the input of inference. Thank you for the feed back!
